apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: backend-tests-go-bkgnfrhb
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/backend-tests-go-bkgnfrhb:b64e73ec3b3d3ad1a1c7373335643f15d7e28b8c@sha256:320860954eba92b7cf12f6b498b326c8ead9e63ee6f1664bd7a2e1b72e95eaac
          name: container-image
